### ISSUE TITLE
call 911

### ISSUE THREAD

**Issue by arsh786** [ETVargas/OnTheSpectrum#74]
Will calling 911 work?
(at least an attempt, and Ecclesia's not working over break)

**Comment by francestsenn** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/761f7aa1-ef5e-4d1b-98a1-42576d50de76-c6e3042d-d332-4001-a05c-07fa7bef06b0-v1.png?transparent=1&palette=1&width=246)
